### ISSUE TITLE
More publications

### ISSUE THREAD

**Issue by modichirag** [DifferentiableUniverseInitiative/Initiative#3]
I think these fit the bill as well.
I can go ahead and add them if its alright

https://arxiv.org/abs/1907.02330
https://arxiv.org/abs/1903.09049

**Comment by EiffL** [comment]
Great :-D Thanks for that! 
I added you as a contributor. To add papers, here is the procedure:

 1 - Create and checkout a new branch
 2 - Add the ADS bibcode in this list:
https://github.com/DifferentiableUniverseInitiative/Initiative/blob/5809d7fd24caa5077143821f9a895ef54add71f8/docs/_data/_generate_publications_csv.py#L24
 3 - Follow these instructions to update the publications csv file by running that script:
https://github.com/DifferentiableUniverseInitiative/Initiative/blob/5809d7fd24caa5077143821f9a895ef54add71f8/docs/_data/_generate_publications_csv.py#L8
 4 - Commit and Push the update .py file and .csv
 5 - Open a PR

**Comment by EiffL** [comment]
This issue is fixed by #4
